name: Build & Test

on: [push, pull_request]

jobs:
  Ubuntu-1804-gcc:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    env:
      MRUBY_CONFIG: ci/gcc-clang
      TERM: xterm
      CC: gcc
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: ./build.sh
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: mrbmacs-termbox
          path: mruby/bin/mrbmacs-termbox
      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      - name: Test
        run: faketty ./build.sh test

  macOS:
    runs-on: macos-latest
    timeout-minutes: 10
    env:
      MRUBY_CONFIG: ci/gcc-clang
      CC: clang
    steps:
      - uses: actions/checkout@v3
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build
        run: ./build.sh
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: mrbmacs-termbox
          path: mruby/bin/mrbmacs-termbox
      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      - name: Test
        run: faketty ./build.sh test
