name: Build & Test

on: [push, pull_request]

jobs:
  Ubuntu-1804-gcc:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    env:
      MRUBY_CONFIG: ci/gcc-clang
      CC: gcc
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build and test
        run: ./build.sh && ./build.sh test